# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('financial_advisor', 'Financial Advisor'), ('insurance_agent', 'Insurance Agent'), ('attorney', 'Attorney'), ('real_estate_agent', 'Real Estate Agent'), ('tax_pro', 'Tax Pro'), ('mortgage_pro', 'Mortgage Pro')], db_index=True, max_length=30, null=True),
        ),
    ]
