# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-20 10:30
from __future__ import unicode_literals

import conversations.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='teams.Team')),
                ('users', models.ManyToManyField(blank=True, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_related_name': 'conversations',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=conversations.models.path_name)),
                ('position', models.PositiveIntegerField()),
                ('mobile_uid', models.CharField(max_length=64)),
                ('sent', models.BooleanField(default=False)),
                ('recieved', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.Conversation')),
                ('read_by', models.ManyToManyField(blank=True, related_name='readby', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at', 'position'),
                'default_related_name': 'messages',
            },
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together=set([('position', 'conversation')]),
        ),
    ]
